import type { MapaRegiao } from './types'
import { modelosNatureza } from './assets'

const MEIA_LARGURA_MUNDO = 16
const MEIA_PROFUNDIDADE_MUNDO = 16

/**
 * Mapa inicial da região da criação, sem dependência de modelos externos.
 *
 * Os props mantêm corredores livres entre os pontos de interesse para que a
 * exploração continue navegável mesmo quando os fallbacks forem renderizados.
 */
export const mapaCriacao: MapaRegiao = {
  spawn: [4, 2, 12],
  limites: {
    meiaLargura: MEIA_LARGURA_MUNDO,
    meiaProfundidade: MEIA_PROFUNDIDADE_MUNDO,
  },
  props: [
    {
      id: 'prop-pedra-luz',
      ...modelosNatureza.pedra4,
      posicao: [-7, 0, -6],
      escala: [1.4, 0.8, 1.4],
      colisor: {
        forma: 'cuboid',
        meiaExtensao: [0.72, 0.72, 0.72],
        deslocamento: [0, 0.72, 0],
      },
      fallback: { forma: 'esfera', cor: '#d9c7a3' },
    },
    {
      id: 'prop-arvore-vida',
      ...modelosNatureza.arvore1,
      posicao: [7, 0, -7],
      escala: 0.64,
      colisor: {
        forma: 'cuboid',
        meiaExtensao: [0.34, 2.1, 0.34],
        deslocamento: [0, 2.1, 0],
      },
      fallback: { forma: 'cone', cor: '#4f8f5b' },
    },
    {
      id: 'prop-lago-sereno',
      posicao: [8, 0, 4],
      escala: [3.2, 0.12, 2.2],
      collider: false,
      fallback: { forma: 'cilindro', cor: '#65a9c7' },
    },
    {
      id: 'prop-colina-verde',
      posicao: [-8, 0, 5],
      escala: [3, 1.8, 2.6],
      collider: 'hull',
      fallback: { forma: 'esfera', cor: '#73a65b' },
    },
    {
      id: 'prop-arco-do-jardim',
      posicao: [0, 0, -12],
      escala: [2.8, 2.6, 0.7],
      collider: 'cuboid',
      fallback: { forma: 'caixa', cor: '#c28b52' },
    },
    {
      id: 'prop-campo-aberto',
      ...modelosNatureza.gramaAlta,
      posicao: [0, 0, 7],
      escala: [2.6, 0.75, 2.6],
      collider: false,
      fallback: { forma: 'caixa', cor: '#a3c96b' },
    },
    {
      id: 'prop-criacao-arvore-noroeste',
      ...modelosNatureza.arvore2,
      posicao: [-14, 0, -13],
      rotacao: 0.5,
      escala: 0.44,
      collider: false,
      fallback: { forma: 'cone', cor: '#4f8f5b' },
    },
    {
      id: 'prop-criacao-arvore-nordeste',
      ...modelosNatureza.arvore3,
      posicao: [14, 0, -14],
      rotacao: -0.6,
      escala: 0.5,
      collider: false,
      fallback: { forma: 'cone', cor: '#5a965d' },
    },
    {
      id: 'prop-criacao-arvore-oeste',
      ...modelosNatureza.arvore4,
      posicao: [-14, 0, 1],
      rotacao: -0.35,
      escala: 0.5,
      collider: false,
      fallback: { forma: 'cone', cor: '#4f8f5b' },
    },
    {
      id: 'prop-criacao-arvore-leste',
      ...modelosNatureza.arvore5,
      posicao: [14, 0, 0],
      rotacao: 0.8,
      escala: 0.68,
      collider: false,
      fallback: { forma: 'cone', cor: '#5a965d' },
    },
    {
      id: 'prop-criacao-arvore-sudoeste',
      ...modelosNatureza.arvore3,
      posicao: [-14, 0, 14],
      rotacao: 0.2,
      escala: 0.46,
      collider: false,
      fallback: { forma: 'cone', cor: '#5a965d' },
    },
    {
      id: 'prop-criacao-arvore-sudeste',
      ...modelosNatureza.arvore2,
      posicao: [14, 0, 14],
      rotacao: -0.75,
      escala: 0.44,
      collider: false,
      fallback: { forma: 'cone', cor: '#4f8f5b' },
    },
    {
      id: 'prop-criacao-grama-vegetacao',
      ...modelosNatureza.gramaBaixa,
      posicao: [-10.5, 0, 7.2],
      rotacao: 0.3,
      escala: [6.5, 1.8, 6.5],
      collider: false,
      fallback: { forma: 'cone', cor: '#75a85f' },
    },
    {
      id: 'prop-criacao-flor-vegetacao-a',
      ...modelosNatureza.arbustoFlorido,
      posicao: [-8.6, 0, 9.5],
      rotacao: -0.4,
      escala: 1.15,
      collider: false,
      fallback: { forma: 'esfera', cor: '#8abf68' },
    },
    {
      id: 'prop-criacao-flor-vegetacao-b',
      ...modelosNatureza.folhagem,
      posicao: [-13, 0, 6],
      rotacao: 0.55,
      escala: 1.2,
      collider: false,
      fallback: { forma: 'esfera', cor: '#77a95f' },
    },
    {
      id: 'prop-criacao-pedra-lago',
      ...modelosNatureza.pedra5,
      posicao: [11.8, 0, 2.2],
      rotacao: 0.45,
      escala: 1.05,
      collider: false,
      fallback: { forma: 'esfera', cor: '#c8b58e' },
    },
  ],
  artes2D: [
    {
      id: 'arte-criacao-caminho-luz',
      arquivo: '/art/creation/light/light-path-unlocked.svg',
      posicao: [5.5, 0.015, 7],
      escala: [10, 3.2],
      modo: 'chao',
      rotacao: -0.2,
      opacidade: 0.78,
    },
    {
      id: 'arte-criacao-primeiro-brilho',
      arquivo: '/art/creation/light/first-glow.svg',
      posicao: [7.5, 3.8, -13.8],
      escala: [12, 5.2],
      opacidade: 0.72,
    },
    {
      id: 'arte-criacao-nucleo-luz',
      arquivo: '/art/creation/light/divine-light-core.svg',
      posicao: [10, 2.15, -10.35],
      escala: [3.8, 3.8],
      opacidade: 0.86,
    },
    {
      id: 'arte-criacao-rochas-iluminadas',
      arquivo: '/art/creation/light/illuminated-rocks.svg',
      posicao: [-7, 1.15, -6.4],
      escala: [5.4, 2.3],
      opacidade: 0.9,
    },
    {
      id: 'arte-criacao-particulas-luz',
      arquivo: '/art/creation/light/light-particles.svg',
      posicao: [9.2, 3.1, -9.8],
      escala: [5, 3.9],
      opacidade: 0.62,
    },
    {
      id: 'arte-criacao-animal-elefante',
      arquivo: '/art/animals/kenney/elephant.png',
      posicao: [13.2, 1.25, 6.1],
      escala: [1.5, 1.35],
      opacidade: 0.94,
    },
    {
      id: 'arte-criacao-animal-girafa',
      arquivo: '/art/animals/kenney/giraffe.png',
      posicao: [9.2, 1.45, 10.5],
      escala: [1.35, 1.55],
      opacidade: 0.94,
    },
    {
      id: 'arte-criacao-animal-coelho',
      arquivo: '/art/animals/kenney/rabbit.png',
      posicao: [12.8, 1.05, 10.2],
      escala: [0.95, 1.25],
      opacidade: 0.94,
    },
    {
      id: 'arte-criacao-animal-pato',
      arquivo: '/art/animals/kenney/duck.png',
      posicao: [9.1, 0.95, 6.2],
      escala: [1, 1],
      opacidade: 0.94,
    },
  ],
  // IDs públicos aprovados pelo proxy; a referência USFM permanece no backend.
  coletaveis: [
    {
      id: 'coletavel-primeiro-dia',
      historiaId: 'criacao',
      passagemId: 'genesis-1-1',
      posicao: [-11, 1, -11],
      raioAtivacao: 1.5,
      cor: '#f5d76e',
    },
    {
      id: 'coletavel-luz',
      historiaId: 'criacao',
      passagemId: 'genesis-1-3',
      posicao: [10, 1, -10],
      raioAtivacao: 1.5,
      cor: '#ffe9a6',
    },
    {
      id: 'coletavel-vegetacao',
      historiaId: 'criacao',
      passagemId: 'genesis-1-11',
      posicao: [-11, 1, 9],
      raioAtivacao: 1.5,
      cor: '#8dc76b',
    },
    {
      id: 'coletavel-animais',
      historiaId: 'criacao',
      passagemId: 'genesis-1-24',
      posicao: [11, 1, 8],
      raioAtivacao: 1.5,
      cor: '#83c9d8',
    },
    {
      id: 'coletavel-humanidade',
      historiaId: 'criacao',
      passagemId: 'genesis-1-27',
      posicao: [0, 1, 0],
      raioAtivacao: 1.5,
      cor: '#d8a36e',
    },
  ],
}

export default mapaCriacao
